global using Blazored.LocalStorage;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using MudBlazor;
global using MudBlazor.Services;
global using NierReinGachaSimulator;
global using NierReinGachaSimulator.Model;
global using System.Net.Http.Json;
